application: academic-volt-91409
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: main.application
  
# now add library for jinja templating
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest